import localFont from "next/font/local";
import "./globals.css";
import { PlaiaZoneProvider } from "../context/PlaiaZone";
import DarkModeToggle from "@/components/DarkModeToggle";
import { ThemeProvider } from "@/context/ThemeContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-24 dark:bg-[#1f2022]`}
      >
           <PlaiaZoneProvider>  {children} <DarkModeToggle/></PlaiaZoneProvider>
      

       
      </body>
      </ThemeProvider>
    </html>
  );
}
